env_args:
  map_name: protoss_5_vs_5
  use_absorbing_state: true
  trailing_absorbing_state_length: 2

world_model:
  rssm:
    use_act_mask_predictor: true
    use_cont_predictor: true

train:
  gamma: 0.99

logging:
  log_keys_avg: '^log_battle_won$'

